version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: mage2_nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes: &appvolumes
      - ~/Projects/magento2/app/code:/magento2/app/code:delegated
      - ~/Projects/magento2/app/design:/magento2/app/design:delegated
      - ~/Projects/magento2/app/etc:/magento2/app/etc:delegated
      - ~/Projects/magento2/composer.json:/magento2/composer.json:delegated
      - ~/Projects/magento2/composer.lock:/magento2/composer.lock:delegated
      - ./nginx/mage2.conf:/etc/nginx/conf.d/mage2:delegated
      - ./nginx/mage2.local.conf:/etc/nginx/conf.d/mage2.local.conf:delegated
      - ~/Projects/magento2/var/log:/magento2/var/log
      - ~/Projects/magento2/var/report:/magento2/var/report
    networks:
      - network-back

  php:
    build: php
    container_name: mage2_php
    volumes: *appvolumes
    networks:
      - network-back

  db:
    image: mariadb
    container_name: mage2_mariadb
    volumes:
      - "~/databases/magento2:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - network-back

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mage2_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - network-back

  redis:
    image: redis
    container_name: mage2_redis
    ports:
      - "6379:6379"
    networks:
      - network-back

networks:
  network-back:
    driver: bridge